### ISSUE TITLE
수업 전 video 감상문은 어디로 제출하면 되나요?

### ISSUE THREAD

**Issue by skyil7** [sejongresearch/2020.Spring.AI#3]
안녕하세요. 교수님.

깃허브 README 상에 있는 video 감상문 제출은 어떻게 하면 될까요?
혹시 어딘가에 있다면 죄송합니다.. ㅠㅠ 블랙보드 OT 영상에 없는 듯 하여 질문 드립니다.

감사합니다.

**Comment by kimhanui** [comment]
과제1 제출도 블랙보드 어디로 해야하는지 궁금합니다...!

**Comment by big-chan** [comment]
과제 1 제출은 1주차 영상 보시는 곳에 올라가 있습니다

**Comment by big-chan** [comment]
@skyil7 그 video  감상문은 오프라인 수업이 진행된 후 공지 드리겠습니다. 현재는 따로 작성 안해주셔도 될거 같습니다

**Comment by skyil7** [comment]
감사합니다!
