### ISSUE TITLE
교재

### ISSUE THREAD

**Issue by chae52** [sejongresearch/2020.Spring.AI#4]
수업계획서에 나와 있는 주교재("모두를 위한 딥러닝")를 검색해도 찾을 수 없습니다. 
혹시 링크를 올려주시거나 검토해 주실 수 있나요?

**Comment by big-chan** [comment]
https://hunkim.github.io/ml/
모두를 위한 딥려닝은 위 링크의 강의를 뜻합니다. 인공지능 기초로 강의 입니다.
따로 교재는 없습니다.

**Comment by chae52** [comment]
감사합니다
